# Generated by Django 3.1.7 on 2021-03-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Types'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name_plural': 'Varieties'},
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
